=== brianmay/openflightplanner/aircraft.dtd
<!ELEMENT Aircraft  (Callsign,Full_Callsign,Type,Approved_Type,Colour,Description,Equipment,Wake,Fuel_Consumption,Air_Speed,Limits,Loading,COG,Basic_Empty_Weight,Arm)>
<!ATTLIST Aircraft
        id              ID      #IMPLIED
>

<!ELEMENT Callsign (#PCDATA)>
<!ELEMENT Full_Callsign (#PCDATA)>
<!ELEMENT Type (#PCDATA)>
<!ELEMENT Approved_Type EMPTY>
<!ELEMENT Colour (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Wake (#PCDATA)>
<!ELEMENT Basic_Empty_Weight (#PCDATA)>

<!-- Equipment -->
<!ELEMENT Equipment (DME?,GNSS?,INS?,RNP?,UHF?,ADF?,VOR?,HF?,DLink?,TAX?,VHF?,GPS?,ADS?,SSR?)>
<!ELEMENT DME EMPTY>
<!ELEMENT GNSS EMPTY>
<!ELEMENT INS EMPTY>
<!ELEMENT RNP EMPTY>
<!ELEMENT UHF EMPTY>
<!ELEMENT ADF EMPTY>
<!ELEMENT VOR EMPTY>
<!ELEMENT HF EMPTY>
<!ELEMENT DLink EMPTY>
<!ELEMENT TAC EMPTY>
<!ELEMENT VHF EMPTY>
<!ELEMENT GPS EMPTY>
<!ELEMENT ADS EMPTY>
<!ELEMENT SSR (#PCDATA)>

<!-- Fuel_Consumption and Airspeed -->
<!ELEMENT Fuel_Consumption (Climb,Cruise,Descend,Holding,Taxi,AWK)>
<!ELEMENT Air_Speed (Climb,Cruise,Descend)>
<!ELEMENT Climb (#PCDATA)>
<!ELEMENT Cruise (#PCDATA)>
<!ELEMENT Descend (#PCDATA)>
<!ELEMENT Holding (#PCDATA)>
<!ELEMENT Taxi (#PCDATA)>
<!ELEMENT AWK (#PCDATA)>

<!-- Limits -->
<!ELEMENT Limits (MTOW,MLW,MZFW)>
<!ELEMENT MTOW (#PCDATA)>
<!ELEMENT MLW (#PCDATA)>
<!ELEMENT MZFW (#PCDATA)>

<!-- Loading -->
<!ELEMENT Loading (Seat+,Fuel_Tank+)>

<!-- Seat and Fuel Tank -->
<!ELEMENT Seat (Description,Arm,Type,Maximum)>
<!ELEMENT Fuel_Tank (Description,Arm,Maximum)>
<!ELEMENT Arm (#PCDATA)>
<!ELEMENT Maximum (#PCDATA)>

<!-- COG -->
<!ELEMENT COG (Entry+)>

<!-- Entry -->
<!ELEMENT Entry (Arm,Weight)>
<!ELEMENT Weight (#PCDATA)>

=== brianmay/openflightplanner/tests/data/aircraft.xml
<?xml version="1.0"?>
<!DOCTYPE Aircraft SYSTEM "../../aircraft.dtd">
<Aircraft>
  <Callsign>CWW</Callsign>
  <Full_Callsign>VH-CWW</Full_Callsign>
  <Type>PA28</Type>
  <Approved_Type/>
  <Colour>Red/White</Colour>
  <Description>Piper Warrior</Description>
  <Equipment>
    <VHF/>
    <SSR>Mode_C</SSR>
  </Equipment>
  <Wake>Light</Wake>
  <Fuel_Consumption>
    <Climb>30</Climb>
    <Cruise>30</Cruise>
    <Descend>30</Descend>
    <Holding>30</Holding>
    <Taxi>30</Taxi>
    <AWK>30</AWK>
  </Fuel_Consumption>
  <Air_Speed>
    <Cruise>100</Cruise>
    <Climb>100</Climb>
    <Descend>100</Descend>
  </Air_Speed>
  <Limits>
    <MTOW>1055</MTOW>
    <MLW>1055</MLW>
    <MZFW>1055</MZFW>
  </Limits>
  <Loading>
    <Seat>
      <Description>Front Row</Description>
      <Arm>2044.7</Arm>
      <Type>Always_A_Seat</Type>
      <Maximum>100</Maximum>
    </Seat>
    <Seat>
      <Description>Front Row</Description>
      <Arm>2044.7</Arm>
      <Type>Always_A_Seat</Type>
      <Maximum>100</Maximum>
    </Seat>
    <Seat>
      <Description>Back Row</Description>
      <Arm>2999.7</Arm>
      <Type>Always_A_Seat</Type>
      <Maximum>100</Maximum>
    </Seat>
    <Seat>
      <Description>Back Row</Description>
      <Arm>2999.7</Arm>
      <Type>Always_A_Seat</Type>
      <Maximum>100</Maximum>
    </Seat>
    <Fuel_Tank>
      <Description>Main Fuel Tanks</Description>
      <Arm>2413.0</Arm>
      <Maximum>181</Maximum>
    </Fuel_Tank>
  </Loading>
  <COG>
    <Entry>
      <Arm>2110</Arm>
      <Weight>600</Weight>
    </Entry>
    <Entry>
      <Arm>2110</Arm>
      <Weight>900</Weight>
    </Entry>
    <Entry>
      <Arm>2220</Arm>
      <Weight>1055</Weight>
    </Entry>
    <Entry>
      <Arm>2370</Arm>
      <Weight>1055</Weight>
    </Entry>
    <Entry>
      <Arm>2370</Arm>
      <Weight>600</Weight>
    </Entry>
  </COG>
  <Basic_Empty_Weight>674</Basic_Empty_Weight>
  <Arm>2205</Arm>
</Aircraft>

=== brianmay/openflightplanner/sample/aircraft.xml
<?xml version="1.0"?>
<!DOCTYPE Aircraft SYSTEM "../aircraft.dtd">
<Aircraft>
  <Callsign>CJR</Callsign>
  <Full_Callsign>VH-CJR</Full_Callsign>
  <Type>PA28</Type>
  <Approved_Type/>
  <Colour>Red/White</Colour>
  <Description>Piper Archer</Description>
  <Equipment>
    <VHF/>
    <SSR>Mode_C</SSR>
  </Equipment>
  <Wake>Light</Wake>
  <Fuel_Consumption>
    <Climb>36</Climb>
    <Cruise>36</Cruise>
    <Descend>36</Descend>
    <Holding>36</Holding>
    <Taxi>36</Taxi>
    <AWK>36</AWK>
  </Fuel_Consumption>
  <Air_Speed>
    <Climb>110</Climb>
    <Cruise>110</Cruise>
    <Descend>110</Descend>
  </Air_Speed>
  <Limits>
    <MTOW>1156</MTOW>
    <MLW>1156</MLW>
    <MZFW>1156</MZFW>
  </Limits>
  <Loading>
    <Seat>
      <Description>Front Row</Description>
      <Arm>2044.7</Arm>
      <Type>Always_A_Seat</Type>
      <Maximum>100</Maximum>
    </Seat>
    <Seat>
      <Description>Front Row</Description>
      <Arm>2044.7</Arm>
      <Type>Always_A_Seat</Type>
      <Maximum>100</Maximum>
    </Seat>
    <Seat>
      <Description>Back Row</Description>
      <Arm>2999.7</Arm>
      <Type>Always_A_Seat</Type>
      <Maximum>100</Maximum>
    </Seat>
    <Seat>
      <Description>Back Row</Description>
      <Arm>2999.7</Arm>
      <Type>Always_A_Seat</Type>
      <Maximum>100</Maximum>
    </Seat>
    <Seat>
      <Description>Baggage</Description>
      <Arm>3627.1</Arm>
      <Type>Not_A_Seat</Type>
      <Maximum>91</Maximum>
    </Seat>
    <Fuel_Tank>
      <Description>Main Fuel Tanks</Description>
      <Arm>2413.0</Arm>
      <Maximum>181</Maximum>
    </Fuel_Tank>
  </Loading>
  <COG>
    <Entry>
      <Arm>2080</Arm>
      <Weight>600</Weight>
    </Entry>
    <Entry>
      <Arm>2080</Arm>
      <Weight>900</Weight>
    </Entry>
    <Entry>
      <Arm>2250</Arm>
      <Weight>1156</Weight>
    </Entry>
    <Entry>
      <Arm>2370</Arm>
      <Weight>1156</Weight>
    </Entry>
    <Entry>
      <Arm>2370</Arm>
      <Weight>600</Weight>
    </Entry>
  </COG>
  <Basic_Empty_Weight>676</Basic_Empty_Weight>
  <Arm>2218</Arm>
</Aircraft>
