=== brianmay/openflightplanner/flightplan.dtd
<!ELEMENT Flightplan  (Flight+)>
<!ATTLIST Flightplan
        id              ID      #IMPLIED
>

<!-- Flight -->
<!ELEMENT Flight (Departure_Time,Takeoff,Load?,Leg+,Landing)>
<!ELEMENT Departure_Time (#PCDATA)>
<!ELEMENT Takeoff (#PCDATA)>
<!ELEMENT Landing (#PCDATA)>

<!-- Load -->
<!ELEMENT Load (Seat*,Fuel_Tank*)>

<!-- Seat -->
<!ELEMENT Seat (Weight,Content)>
<!ELEMENT Weight (#PCDATA)>
<!ELEMENT Content (#PCDATA)>

<!-- Fuel_Tank -->
<!ELEMENT Fuel_Tank (Litres,Type)>
<!ELEMENT Litres (#PCDATA)>
<!ELEMENT Type (#PCDATA)>

<!-- Leg -->
<!ELEMENT Leg ((Distance,Track)?,Altitude,Lowest_Safe_Altitude,Destination,Destination_Altitude?,Wind)>
<!ELEMENT Distance (#PCDATA)>
<!ELEMENT Track (#PCDATA)>
<!ELEMENT Altitude (#PCDATA)>
<!ELEMENT Lowest_Safe_Altitude (#PCDATA)>
<!ELEMENT Destination (#PCDATA)>
<!ELEMENT Destination_Altitude (#PCDATA)>
<!ELEMENT Wind (#PCDATA)>

=== brianmay/openflightplanner/tests/data/flightplan.xml
<?xml version="1.0"?>
<!DOCTYPE Flightplan SYSTEM "../../flightplan.dtd">
<Flightplan>
  <Flight>
    <Takeoff>YLIL</Takeoff>
    <Load>
      <Seat>
        <Weight>60</Weight>
        <Content>Passenger</Content>
      </Seat>
      <Fuel_Tank>
        <Litres>180</Litres>
      </Fuel_Tank>
    </Load>

    <Leg>
      <Departure_Time>2003-1-2 11:22:33</Departure_Time>
      <Distance>10</Distance>
      <Track>100</Track>
      <Altitude>1500</Altitude>
      <Lowest_Safe_Altitude>1500</Lowest_Safe_Altitude>
      <Destination>YLIL</Destination>
      <Destination_Altitude>1500</Destination_Altitude>
      <Wind>230/15</Wind>
    </Leg>

    <Landing>YLIL</Landing>

    <Alternate>
      <Departure_Time>2003-1-2 11:22:33</Departure_Time>
      <Distance>10</Distance>
      <Track>100</Track>
      <Altitude>1500</Altitude>
      <Lowest_Safe_Altitude>1500</Lowest_Safe_Altitude>
      <Destination>YLIL</Destination>
      <Destination_Altitude>1500</Destination_Altitude>
      <Wind>230/15</Wind>
    </Alternate>
  </Flight>
</Flightplan>

=== brianmay/openflightplanner/tests/data/flight.xml
<?xml version="1.0"?>
<!DOCTYPE Flight SYSTEM "../../flightplan.dtd">
<Flight>
  <Departure_Time>2003-1-2 11:22:33</Departure_Time>
  <Takeoff>YLIL</Takeoff>
  <Load>
    <Seat>
      <Weight>60</Weight>
      <Content>Passenger</Content>
    </Seat>
    <Fuel_Tank>
      <Litres>180</Litres>
    </Fuel_Tank>
  </Load>

  <Leg>
    <Distance>10</Distance>
    <Track>100</Track>
    <Altitude>1500</Altitude>
    <Lowest_Safe_Altitude>1500</Lowest_Safe_Altitude>
    <Destination>YLIL</Destination>
    <Destination_Altitude>1500</Destination_Altitude>
    <Wind>230/15</Wind>
  </Leg>

  <Landing>YLIL</Landing>

  <Alternate>
    <Distance>10</Distance>
    <Track>100</Track>
    <Altitude>1500</Altitude>
    <Lowest_Safe_Altitude>1500</Lowest_Safe_Altitude>
    <Destination>YLIL</Destination>
    <Destination_Altitude>1500</Destination_Altitude>
    <Wind>230/15</Wind>
  </Alternate>
</Flight>
